# Map the board model to the directory
title = "Board Mapping"

[boards]

    # List the board name
    [boards.nrf52840dk]
  	path = "./boards/nordic/nrf52840dk" # Path to the board dir in tock repo
  	series = "nrf52dk" # Series ID used for tockloader
	mapping = [
	    # ["Pin number on RPi", "Pin ID on board"]
	    ["22", "P0 13"]
	]
